export const content = [
    { title: "Feliz 1 ano de nós! ❤️", content: "Olá meu amor! Hoje é o nosso tão esperado dia, o nosso aniversário... Vamos relembrar um pouco nossa linda história?", imageSrc: "" },
    { title: "Primeiro Encontro", content: "O dia em que tudo deu certo e nos conhecemos finalmente.", imageSrc: "primeiroencontro.jpg" },
    { title: "Primeiro Encontro", content: "Cada risada dada e até mesmo a dor de eu ter te machucado... a gente releva né?.", imageSrc: "primeiroencontro1.jpg" },
    { title: "Me apaixonando por seu jeito..", content: "Mas seu jeito encantador me conquistou desde o início.", imageSrc: "segundoencontro.jpg" },
    { title: "Por seu sorriso", content: "Quando vi o sorriso, mesmo sendo a segunda vez, é impossivel o coração não palpitar", imageSrc: "segundoencontro2.jpg" },
    { title: "Mostrando que treina", content: "Fomos treinar pela primeira vez pra nunca mais kkkkkk", imageSrc: "indotreinar.jpg" },
    { title: "Franga Plus", content: "Aqui mostramos a nossa força hein, o orgulho da academia", imageSrc: "treinando.jpg" },
    { title: "Me deixando sem palavras...", content: "Esse dia foi o dia que quase infartei de alegria e ao mesmo tempo fiquei sem palavras", imageSrc: "floresprimeiravez.jpeg" },
    { title: "Chamadas com você..", content: "Eu amava te ver dormir em todas as nossas chamadas", imageSrc: "elamimindo.jpg" },
    { title: "Saindo escondido...", content: "O dia em que você pegou uber a noite para podermos tomar nosso açaí e foi um dos melhores momentos", imageSrc: "comendoacai1veez.jpg" },
    { title: "Açaí é sempre bom", content: "Açaí, a barca que comemos é inesquecivel, mas a forma em que você estava linda... senhor", imageSrc: "primeiravezcomendoacai.jpg" },
    { title: "Dia que fui sincera..", content: "O dia em que você contou a minha mãe sobre nos, mas também quando me deu o quadro de Demon Slayer!!", imageSrc: "elalinda.png" },
    { title: "Você tomando a frente", content: "Aquele momento em que você tomou a frente, mesmo me deixando nervosa, eu não tive receio", imageSrc: "diadecontarqueestavamosficando.png" },
    { title: "Um olhar fascinante", content: "Seu olhar é me apaixona todos os dias. Mas quando cada vez que nossos olhos se encontravam, sentia o mundo parar.", imageSrc: "beijoo.jpeg" },
    { title: "Um beijo inesquecível", content: "Esse beijo gostoso, maravilhoso, apaixonado, que você me tira de órbita e traz de volta em segundos...", imageSrc: "beijoo2.jpeg" },
    { title: "Eu te amo", content: "Cada abraço seu é um presente. Cada sorriso é uma razão para me apaixonar mais. Te amo de formas que não posso explicar.", imageSrc: "teamo.jpg" },
    { title: "Eu te amo", content: "E isso foi o que senti quando você sussurrou em meu ouvido que me amava, o primeiro Eu Te Amo", imageSrc: "teamo2.jpg" },
    { title: "Você faz meu coração palpitar", content: "Quando você está por perto, meu coração dispara, e tudo ao redor parece brilhar. Te amo mais a cada segundo.", imageSrc: "comendomec.png" },
    { title: "Seu cheiro é tão bom", content: "Seu cheiro é o que faz meu coração bater mais forte, me lembrando sempre da sensação de estar contigo.", imageSrc: "comendomec2.png" },
    { title: "Nosso ponto de encontro", content: "Visitamos o Park City mais vezes do que eu visitei o Dom Pedro!! Mas sempre foi para poder estar contigo", imageSrc: "elalindatomamosmilkshake.jpeg" },
    { title: "Novos estilos", content: "O dia que entramos na Renner e praticamente trouxe uma nova perspectiva de estilo para mimm! Minha estilista??", imageSrc: "mudancanoestilo.jpg" },
    { title: "Piscina é ótimo", content: "Cada momento com você é um momento especial. Nunca pensei ir no clube aproveitar a piscina, mas com você foi algo mágico e muito gostoso!", imageSrc: "piscinanabosch.png" },
    { title: "Mas com você é perfeito", content: "Até os dias mais simples são perfeitos ao seu lado. Cada momento contigo é cheio de felicidade e amor.", imageSrc: "piscinanabosch2.png" },
    { title: "Você é meu par", content: "Você é a pessoa que me completa. Com você, me sinto em casa, sempre feliz.", imageSrc: "fotofofa.jpg" },
    { title: "Os olhos que me encantam", content: "Eu sinto como seus olhos tivessem algum poder. Cada olhar é uma sedução, amor, carinho, excitação e paixão.", imageSrc: "fotofofa1.jpg" },
    { title: "Amo sua boca", content: "Cada beijo seu é único. Amo cada momento que eu possa te beijar, é como se o tempo parasse.", imageSrc: "agentelinda.jpg" },
    { title: "Amo seu olhar", content: "Seu olhar me diz tudo, desde quando esta brava a quando esta cansada, com fome, com sono, animada e apaixonada.", imageSrc: "mcnoshop.jpeg" },
    { title: "Amo seus gostos", content: "Cada gosto que temos diferente me deixa curiosa, você sempre fica animada com algo que gosta e isso me deixa animada.", imageSrc: "momentoss.jpeg" },
    { title: "Amo estar com você", content: "Não importa onde estamos, o que importa é estar com você. Cada momento contigo é único e perfeito.", imageSrc: "momentinnho.jpeg" },
    { title: "Minha mestre yoda??", content: "Você sempre tem as respostas certas, me ensinando a ver a vida de um jeito diferente e amoroso.", imageSrc: "mestreypda2.jpg" },
    { title: "Uma arvorezinha?", content: "Aqui você esta tão fofaa, realmente parece uma arvorezinha, da vontade de morder você", imageSrc: "mestryoda.jpg" },
    { title: "Momentos leves com você", content: "Com você, até os momentos mais leves se tornam inesquecíveis. Cada segundo ao seu lado é uma lembrança para a vida toda.", imageSrc: "top.jpeg" },
    { title: "Não consigo conter a felicidade", content: "Minha felicidade é você. Cada momento ao seu lado é uma explosão de alegria e amor.", imageSrc: "tooop.jpeg" },
    { title: "Estar em seu abraço", content: "Seu abraço é o lugar onde me sinto em paz. Sempre que estou te abraçando, tudo faz sentido.", imageSrc: "abracoo.jpeg" },
    { title: "Ver você aprontando", content: "Te ver fazer as coisas que ama me faz rir e me apaixono ainda mais por seu jeito único de ser e ainda com esse sorrisinhoo.", imageSrc: "pintandoparede.jpg" },
    { title: "Me apaixonar ainda mais por seu sorriso", content: "Cada vez que você sorri, meu coração se derrete. Seu sorriso é o meu lugar favorito no mundo.", imageSrc: "sorrisolindodela.jpeg" },
    { title: "Que sorriso lindo...", content: "Não outras palavras a não ser que esse seu sorriso é perfeito, mas não por causa de seus dentes, mas sim pelo que ele passa", imageSrc: "sorrisolindoo.jpeg" },
    { title: "O sorriso sapeca", content: "Aquele sorriso que é só seu, cheio de charme e malícia. Me derreto toda vez que vejo.", imageSrc: "festajunina.png" },
    { title: "Casalzão da porra", content: "Aqui a gente esta o puro casalzão da porra mesmo né? O momento pós te apresentar para minha familia", imageSrc: "festajunina2.jpg" },
    { title: "As flores", content: "As flores que te dei nesse dia é como um símbolo do nosso amor: simples, mas cheia de beleza e intensidade.", imageSrc: "seopastel.jpg" },
    { title: "Você sendo a mais linda", content: "Em todos os momentos, você sempre será a mais linda, como consegue ser tão perfeita?? Meu deuss", imageSrc: "seopastel2.jpg" },
    { title: "Que elegância...", content: "Nossa elegancia, vestimenta e porte, ninguem nos supera aqui! Fomos as mais lindas e somos as mais lindas", imageSrc: "minhaform.jpg" },
    { title: "Combinamos como o mar e o céu", content: "Juntos somos a combinação perfeita. Como o mar e o céu, com harmonia e muito contraste", imageSrc: "minhaforma.jpg" },
    { title: "Sou apaixonada por te ver sorrir", content: "Sim, posso falar quantas vezes forem necessarias, você tem o sorriso mais lindo e apaixonante.", imageSrc: "maniadechurras.jpg" },
    { title: "Sou apaixonada em te apreciar", content: "Admiro tudo em você, desde o jeito como você sorri até a forma como você cuida de mim. Cada detalhe me faz te amar mais.", imageSrc: "saidalindasmaniachurras.jpg" },
    { title: "Te ver feliz comendo", content: "Te ver comendo algo que você ama me faz sorrir também, esse momento é cheio de risadas e também muita satisfação... se a comida for boa.", imageSrc: "brutus1.jpg" },
    { title: "O mau humor sai!!", content: "Apos comer, sempre o mau humor da fome sai ne?? Isso também é uma boa vantagem e os doces entãoo", imageSrc: "fogaomineiro.jpg" },
    { title: "Estar com você é um presente", content: "Você é o meu maior presente. Cada instante ao seu lado é um momento de felicidade.", imageSrc: "reidocupim1.png" },
    { title: "Você é meu tesão diário", content: "Você me encanta todos os dias. Cada olhar, cada gesto, me faz querer você ainda mais.", imageSrc: "reidocupim1_1.png" },
    { title: "Cada momento", content: "Cada segundo ao seu lado é um presente que nunca vou deixar de valorizar.", imageSrc: "topp.jpg" },
    { title: "Cada brincadeira", content: "Quando temos momentos leves com bricandeiras é algo muito gostoso que nunca quero parar de viver.", imageSrc: "momento.jpg" },
    { title: "Cada discussão", content: "Mesmo nas discussões e até mesmo desentendimentos, conseguimos continuar superando e passando pelo problema", imageSrc: "shopp.jpg" },
    { title: "Cada comida que comemos", content: "Até nas coisas simples, compartilhar uma comida boa junto com você, eu fico feliz", imageSrc: "brutus.jpg" },
    { title: "Chegamos e demos o primeiro passo", content: "O primeiro passo foi dado, e com você ao meu lado.", imageSrc: "chavesdecasa.jpg" },
    { title: "Para o nosso futuro", content: "Juntas, nosso futuro será uma linda história que escrevemos a cada dia.", imageSrc: "fotodacomecasachave.jpg" },
    { title: "Primeiro jantar", content: "O primeiro jantar nosso momento mais especial dentro de nossa casa, nosso primeiro momento romântico", imageSrc: "primeirasurpresacasa.jpg" },
    { title: "A luz de velas", content: "Um jantar a luz de velas, me deu um trabalhinho... Mas tudo valeu a pena quando seus olhos brilharam de felicidade meu amor", imageSrc: "primeirasurpresa1.jpg" },
    { title: "Meu presente é você", content: "Você é o presente mais precioso que a vida me deu, e a cada dia sou mais grata por isso.", imageSrc: "diaqueelatavalinda.jpg" },
    { title: "Você torna tudo especial", content: "Com você, cada momento se torna especial e único, como se o tempo parasse só para nós.", imageSrc: "meuniver.jpg" },
    { title: "Você meu conforto", content: "Seu abraço é o meu pilar, onde encontro paz e amor a cada instante que passamos juntas.", imageSrc: "anonovo.jpg" },
    { title: "Seu abraço é minha casa", content: "Em seus braços, encontro meu lar, meu porto seguro, onde tudo faz sentido.", imageSrc: "abraço.jpeg" },
    { title: "Compartilhar memórias com você", content: "Cada memória que criamos juntas será para sempre guardada no meu coração.", imageSrc: "estacaobarao.jpeg" },
    { title: "Deixa tudo mais divertido e apaixonante", content: "Com você, até os momentos mais simples se tornam cheios de diversão e amor.", imageSrc: "estacaobarao2.jpeg" },
    { title: "Você é meu orgulho", content: "Você é a razão do meu sorriso, meu maior orgulho, e o amor da minha vida.", imageSrc: "donaglice2.jpeg" },
    { title: "Você é uma pessoa excepcional", content: "Cada dia ao seu lado me faz admirar mais a pessoa incrível que você é.", imageSrc: "donaglice2_2.jpg" },
    { title: "Contagiante e empolgante", content: "Seu amor e energia tornam minha vida mais contagiante e empolgante a cada dia.", imageSrc: "donaglice2_3.jpeg" },
    { title: "A cada segundo com você", content: "Cada segundo ao seu lado é um momento onde tenho um mix de emoção e sentimentos", imageSrc: "donaglice_4.jpeg" },
    { title: "Eu posso aprender ainda mais", content: "Com você, aprendo a ser uma pessoa melhor a cada dia, com amor e paciência.", imageSrc: "donaglice2_5.jpeg" },
    { title: "Podemos aprender ainda mais", content: "A cada dia, juntas, temos muito mais a aprender e a ensinar um ao outro.", imageSrc: "donaglice2_7.jpg" },
    { title: "Evoluir por você", content: "Evoluir ao seu lado é o maior presente, porque com você, me torno uma pessoa melhor.", imageSrc: "praia.webp" },
    { title: "Evoluir por nós", content: "Nosso amor é uma evolução constante, e a cada dia mais forte, mais bonito, mais verdadeiro.", imageSrc: "praia2.webp" },
    { title: "Para ter ver leve", content: "Com você, tudo fica mais leve, e cada momento se torna mais brilhante e feliz.", imageSrc: "pordosol.jpg" },
    { title: "Para te fazer feliz", content: "Minha missão na vida é te fazer feliz, porque sua felicidade é a minha, seu sorriso é o meu.", imageSrc: "pordosol2.jpg" },
    { title: "E sempre trazer esse seu talento na cozinha", content: "É um dos motivos que agradeço todos os dias a mulher que tenho!! Que comida maravilhosa essa que tu faaaz", imageSrc: "comida.jpg" },
    { title: "E trazer cada dia mais felicidade", content: "Fico feliz em estar passando e divindo minha vida com você! O amor da minha vida.", imageSrc: "comida2.jpg" },
    { title: "Nosso Futuro", content: "E essa história continua... para sempre ao seu lado. \n\n Eu te amo, Arianne", imageSrc: "" },
];
